### ISSUE TITLE
Failed to uncompress data

### ISSUE THREAD

**Issue by felipeparpinelli** [meabed/memcached-php-backup-restore#1]
I have one doubt. When i try to do a backup in memcached with little keys, all works fine, but when i try to do this with a lot of data, i got the following error message:
"PHP Notice:  MemcachePool::get(): Failed to uncompress data in /path/to/memcached-php-backup-restore/m.php on line 25" 

Thanks for your help.

**Comment by emanuelecasadio** [comment]
I have got the same problem.

**Comment by meabed** [comment]
Could you share content or var_dump of the keys and data the fails, it could be binary data or something that couldn't be unserialised. if this is the case i will change the operation instead of serialise to binary pack / unpack then i think this will solve the problem.
