### ISSUE TITLE
Does not save backup to disk under OpenSUSE LEAP 42.2, PHP 7.0.6

### ISSUE THREAD

**Issue by acrolink** [meabed/memcached-php-backup-restore#4]
I have only tested under OpenSUSE LEAP 42.2, PHP 7.0.6 .. I followed the instruction, no output is shown in shell and no backup file is saved to disk. Any idea what might be happening here? Thank you.

**Comment by meabed** [comment]
Hey @acrolink thanks for opening the issue, I have rewrote the script and add tests and CI as well.
Please try it again and let me know if the issue still persist.
Thank you again 👍
