### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by boooch** [meabed/memcached-php-backup-restore#5]
Memory leaks
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 72 bytes) in /home/boooch/m.php on line 105

**Comment by meabed** [comment]
Hey @boooch thanks for opening the issue, I have rewrote the script and add tests and CI as well.
Please try it again and let me know if the issue still persist.
Thank you again 👍
