### ISSUE TITLE
File option is not working

### ISSUE THREAD

**Issue by zjagust** [meabed/memcached-php-backup-restore#7]
ENV: Ubuntu 18.04 with php7.2

$ php /usr/local/sbin/m.php -h 127.0.0.1 -p 11211 -f memcache.txt -op backup
Memcached Data has been saved to file :memcacheData.txt

Whatever I use with -f option is not working. Backup is always saved in memcacheData.txt in current $WORKDIR.

**Comment by meabed** [comment]
Hey @zjagust thanks for opening the issue, I have rewrote the script and add tests and CI as well.
Please try it again and let me know if the issue still persist.
Thank you again 👍
