### ISSUE TITLE
Backup success if no data

### ISSUE THREAD

**Issue by zjagust** [meabed/memcached-php-backup-restore#8]
Same status message will be displayed if there is no data in memcached:

**Memcached Data has been saved to file :memcacheData.txt**

This is misleading and confusing, especially if automated (cron) backups are set. Can you please fix it.

**Comment by meabed** [comment]
Sure I’m gonna fix it today thanks for reporting :)

**Comment by meabed** [comment]
Hey @zjagust thanks for opening the issue, I have rewrote the script and add tests and CI as well.
Please try it again and let me know if the issue still persist.
Thank you again 👍
